# --- General options --- #

# Name of website
title: Strani Anelli

# Short description of your site
description: Personal Portfolio

author:
  name: Strani Anelli, Samuele De Tomasi

copyright: 2018-2028 Strani Anelli, Samuele De Tomasi
keywords_sito:
  - creative personal
  - resume
  - cv
  - portfolio
  - personal
  - developer

sezioni:
  about:
      titolo: About Strani Anelli
      contenutoh2: I'm an indie developer focused on experimenting things!
      testo1: Hello, I'm Samuele aka Strani Anelli and I'm appassionate about tech stuff.
        Over the years I experimented on many branch - now I'm exploring web technology and game development.
        I can use Electron, Vue.js and Construct 3 and I'm studing TensorFlow.
      testo2: I love testing new things and I am strongly convinced that <strong>learning one new thing every day is the way to find happiness</strong>.
      skills:
        - Electron
        - Vue.js
        - Construct 3
        - Front-end development
        - Web Design
        - Game Design
        - Inkscape
        - Liquid

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
